 --1.
 SELECT STUDENT_NAME, STUDENT_ADDRESS
 FROM TB_STUDENT
 ORDER BY STUDENT_NAME;
 
 
 --2.
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

--3.
SELECT STUDENT_NAME, STUDENT_NO, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) LIKE '9%' AND (STUDENT_ADDRESS LIKE '%강원도%' OR STUDENT_ADDRESS LIKE '%경기도%')
ORDER BY STUDENT_NAME;

--4.

SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME ='법학과';

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                                       FROM TB_DEPARTMENT
                                       WHERE DEPARTMENT_NAME ='법학과')
                                       ORDER BY PROFESSOR_SSN;


--5.
SELECT POINT
FROM TB_GRADE
ORDER BY POINT DESC;


SELECT STUDENT_NO, POINT
FROM TB_STUDENT
WHERE POINT = (SELECT POINT
FROM TB_GRADE)
ORDER BY POINT DESC;

SELECT STUDENT_NO, POINT
FROM TB_STUDENT
ORDER BY POINT DESC, STUDENT_NO ASC;

SELECT S.STUDENT_NO,
       G.POINT
FROM TB_STUDENT S
JOIN TB_GRADE G ON S.STUDENT_NO = G.STUDENT_NO
ORDER BY G.POINT DESC, S.STUDENT_NO ASC;


--10.
SELECT G.STUDENT_NO 학번, STUDENT_NAME "학생 이름", ROUND(AVG(POINT),1) "전체 평점"
FROM TB_GRADE G
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_STUDENT USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY G.STUDENT_NO;


--12.
SELECT STUDENT_NAME, TERM_NO AS TERM_NO
FROM TB_STUDENT

JOIN TB_CLASS USING (DEPARTMENT_NO)



--19.
SELECT DEPARTMENT_NAME AS "계열 학과명", ROUND(AVG(POINT), 1) AS 전공평점
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE CATEGORY = (SELECT CATEGORY
                              FROM TB_DEPARTMENT
                              WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME
ORDER BY 1;





