-- 1.
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10) ,
    USE_YN CHAR(1) DEFAULT 'Y'
);
-- 2.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10) 
);

-- 3.
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10) PRIMARY KEY,
    USE_YN CHAR(1) DEFAULT 'Y'
);

--4.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10) NOT NULL
);

--5.
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CATEGORY MODIFY CATEGORY_NAME VARCHAR2(20);

--6.  ALTER TABLE 테이블명 CHANGE 기존컬럼명 새컬럼명 컬럼타입;

ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;

ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;

ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;

--7. ALTER TABLE 테이블명 DROP CONSTRAINT 기존_제약_이름;
ALTER TABLE TB_CLASS_TYPE DROP CONSTRAINT SYS_C007665;
ALTER TABLE TB_CLASS_TYPE ADD CONSTRAINT  PK_TB_CLASS_TYPE PRIMARY KEY (CLASS_TYPE_NO);

ALTER TABLE TB_CATEGORY DROP CONSTRAINT SYS_C007667;
ALTER TABLE TB_CATEGORY ADD CONSTRAINT  PK_CATEGORYE PRIMARY KEY (CATEGORY_NAME);

--8.
INSERT INTO TB_CATEGORY VALUES ('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회', 'Y');
COMMIT;

--9.    - FOREIGN KEY : ALTER TABLE 테이블명 ADD FORIEGN KEY(컬럼명); REFERENCES 참조할 테이블명[(참조할컬럼명)]

CREATE TABLE TB_DEPARTMENT(
    CATEGORY VARCHAR2(20)
);
 ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);


--10.
CREATE VIEW  VW_TB_STUDENT AS
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 학생 이름, STUDENT_ADDRESS AS 주소
FROM TB_STUDENT
WHERE STUDENT_NAME IS NOT NULL;

CREATE OR REPLACE VIEW  VW_TB_STUDENT AS
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 학생 이름, STUDENT_ADDRESS AS 주소, STUDENT_GENDER AS 성별
FROM TB_STUDENT
WHERE STUDENT_NAME IS NOT NULL;







